use_frameworks!

target 'OSRESTfulClient_Example' do
  pod 'OSRESTfulClient', :path => '../'

  target 'OSRESTfulClient_Tests' do
    inherit! :search_paths

    pod 'Kiwi'
  pod 'FBSnapshotTestCase', "~>2.1.4"
  end
end
