source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'OSRESTfulClient_Example', :exclusive => true do
  pod "OSRESTfulClient", :path => "../"
  pod "Mantle", "~>2.0.7"
  pod 'RegExCategories', '~> 1.0'
end

target 'OSRESTfulClient_Tests', :exclusive => true do
  pod "OSRESTfulClient", :path => "../"

  pod 'Kiwi'
end
