source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'OSRESTfulClient_Example' do
  pod "OSRESTfulClient", :path => "../"
  pod "Mantle", "~>2.0.7"
end

target 'OSRESTfulClient_Tests' do
  pod "OSRESTfulClient", :path => "../"
  pod 'Kiwi'
end
